"""empty message

Revision ID: 07f6e404201c
Revises: 90c05db34e87
Create Date: 2019-04-02 14:16:58.606184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f6e404201c'
down_revision = '90c05db34e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_url'), 'post', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_url'), table_name='post')
    # ### end Alembic commands ###
