"""empty message

Revision ID: 90c05db34e87
Revises: b0bcd51a05ee
Create Date: 2019-03-22 00:12:04.865402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c05db34e87'
down_revision = 'b0bcd51a05ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.VARCHAR(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
