name: Fariasweb CD

on:
  push:
    branches:
      - master

jobs:
  deploy:

    name: Deploy the application to production server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Fabric
      run: |
        pip install fabric
    - name: Deploy with Fabric
      run: |
        python deploy.py
      env:
        FARIASWEB_HOST: ${{ secrets.FARIASWEB_HOST }}
        FARIASWEB_PASSWORD: ${{ secrets.FARIASWEB_PASSWORD }}
